server:
  port: 4000
  servlet:
    context-path: /config-server
spring:
  application:
    name: indra-config-service
  cloud:
    config:
      allowOverride: true
      overrideNone: true
      overrideSystemProperties: false
      server:
        git:
          uri: https://github.com/FcondeDev/config-server.git
          searchPaths: '{application}'
          skip-ssl-validation: true
          
  profiles:
    active: master
    
    